version: '3'
services:
  app:
    container_name: beebot
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:
    external: true
